version: "3.5"
services:
  db:
    image: postgres:15
    hostname: db
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: nell_challenge
    ports:
      - "5432:5432"
    deploy:
      resources:
        limits:
          cpus: "0.7"
          memory: "1GB"
    volumes:
      - postgres-db:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./postgresql.conf:/docker-entrypoint-initdb.d/postgresql.conf
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 15s
      timeout: 25s
    command:
      [
        "postgres",
        "-c",
        "config_file=/docker-entrypoint-initdb.d/postgresql.conf",
      ]
  api:
    build: .
    restart: always
    hostname: api
    environment:
      - PORT=8080
      - DATABASE_URL=postgres://postgres:postgres@db:5432/nell_challenge?sslmode=disable
    depends_on:
      db:
        condition: service_healthy
    ports:
      - 8080:8080

volumes:
  postgres-db:

networks:
  default:
    driver: bridge